sudo: false # Explicitly use container-based infrastructure

language: go

go:
  - "1.12"

env:
  - GO111MODULE=on GOPROXY=https://proxy.golang.org
        
notifications:
  email: false

script:
  - make ci-build
  - ./prometheus-pingdom-exporter
